services:

  # Database Service (PostgreSQL)
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT:-5436}:5432" # Externe DB_PORT -> Interne 5432
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Books Management Microservice
  books-service:
    build:
      context: ./backend/books-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dit_books
      - PORT=5001 # écoute interne
    ports:
      - "${BOOKS_PORT:-5016}:5001" # externe BOOKS_PORT -> interne 5001
    restart: always
    depends_on:
      db:
        condition: service_healthy

  # Users Management Microservice
  users-service:
    build:
      context: ./backend/users-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dit_users
      - PORT=5002 # écoute interne
    ports:
      - "${USERS_PORT:-5015}:5002" # externe USERS_PORT -> interne 5002
    restart: always
    depends_on:
      db:
        condition: service_healthy

  # Loans & Returns Management Microservice
  loans-service:
    build:
      context: ./backend/loans-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dit_loans
      - BOOKS_SERVICE_URL=http://books-service:5001
      - USERS_SERVICE_URL=http://users-service:5002
      - PORT=5003 # écoute interne
    ports:
      - "${LOANS_PORT:-5017}:5003" # externe LOANS_PORT -> interne 5003
    restart: always
    depends_on:
      db:
        condition: service_healthy
      books-service:
        condition: service_started
      users-service:
        condition: service_started

  # Frontend & API Gateway (Nginx Reverse Proxy)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-8090}:80" # externe FRONTEND_PORT -> interne 80
    restart: always
    depends_on:
      - books-service
      - users-service
      - loans-service

volumes:
  pg-data:
    driver: local
